{
 "title": "Helldivers2 exporter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Quota errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(hde_api_request_status{status=\"429\"}[1m])))",
     "legendFormat": "429 errors"
    }
   ]
  },
  {
   "title": "API queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(increase(hde_api_request_status[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API HTTP status codes",
   "type": "timeseries",
   "description": "Status codes from the upstream HTTP api\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "(sum by (status) (increase(hde_api_request_status[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "hde_api_request_duration_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}