{
 "title": "Planet details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "planet_name",
    "query": {
     "query": "label_values(hde_planet_max_health, planet)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Liberation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hde_planet_players{planet=\"$planet_name\"}",
     "legendFormat": "Helldivers"
    },
    {
     "expr": "1 - (hde_planet_health{planet=\"$planet_name\"} / hde_planet_max_health{planet=\"$planet_name\"})",
     "legendFormat": "Liberation"
    }
   ]
  },
  {
   "title": "Liberation per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    1 - (\n        hde_planet_health{planet=\"$planet_name\"} / hde_planet_max_health{planet=\"$planet_name\"}\n        ) - (\n            1 - (\n                hde_planet_health{planet=\"$planet_name\"} offset 1h\n                ) / hde_planet_max_health{planet=\"$planet_name\"}\n            )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Helldivers ratio",
   "type": "stat",
   "description": "Percentage of total active helldivers currently on this planet",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hde_planet_players{planet=\"$planet_name\"}) / sum(hde_planet_players)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active helldivers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hde_planet_players{planet=\"$planet_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current liberation prediction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(hde_planet_health{planet=\"$planet_name\"} / (deriv(hde_planet_health{planet=\"$planet_name\"}[1h]) < 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time until liberation predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "abs(hde_planet_health{planet=\"$planet_name\"} / (deriv(hde_planet_health{planet=\"$planet_name\"}[1h]) < 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misc statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missions won",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hde_planet_missions_won{planet=\"$planet_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Missions lost",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hde_planet_missions_lost{planet=\"$planet_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hde_planet_mission_success_rate{planet=\"$planet_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bullet fired",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hde_planet_bullets_fired{planet=\"$planet_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bullet hit",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hde_planet_bullets_hit{planet=\"$planet_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Accuracy",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hde_planet_bullets_hit{planet=\"$planet_name\"} / hde_planet_bullets_fired{planet=\"$planet_name\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}