{
 "title": "WarRoom",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Planet repartition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(hde_planet_players) - sum(topk(5, hde_planet_players))",
     "legendFormat": "Other planets"
    },
    {
     "expr": "topk(5, hde_planet_players) > 0\n",
     "legendFormat": "{{planet}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(hde_planet_players)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Planet health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((hde_planet_health / hde_planet_max_health) * 100) < 99",
     "legendFormat": "{{planet}}"
    }
   ]
  },
  {
   "title": "Liberations",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "abs(hde_planet_health / (deriv(hde_planet_health[1h]) < 0))",
     "legendFormat": "{{planet}}"
    },
    { "expr": "hde_", "legendFormat": "__auto" }
   ]
  }
 ]
}